let score = "33asd"
console.log(typeof score);
//console.log(typeof (score));

let valueInNumber = Number(score);
console.log(typeof valueInNumber);
//console.log(valueInNumber);
let isLoggedIn = 1
let booleanIsLoggedIn = Boolean(isLoggedIn)
console.log(booleanIsLoggedIn);
// 1 => true; 0 => false
// "" => false
// "hitesh" => true
// "33" => 33
// "33abc"=> NaN
let someNumber = 33
let stringNumber = String(someNumber)
console.log(stringNumber);
console.log( typeof stringNumber);